### ISSUE TITLE
How to execute ffmpeg commands in ios app?

### ISSUE THREAD

**Issue by NSBlackMirror** [debugly/StudyFFmpeg#3]
I successfully compiled latest version of ffmpef v4.1 in my ios app but i don't know how to execute ffmpeg commands on local video file?

Suppose i want to convert local mkv video file(located inside ios app) to mp4 file then how can i execute commands using ffmpeg in swift or objective c?

**Comment by debugly** [comment]
Sorry ,I 'm so later !

I think you can copy ffmpeg.c to your project, then mofidy the main function name,
fix  include header file errror,  use return error code instead of exit_program and so on.
