### ISSUE TITLE
链接挂了

### ISSUE THREAD

**Issue by Fogdog525** [debugly/StudyFFmpeg#4]
编译好的FFMpeg库的下载链接挂了

**Comment by debugly** [comment]
依赖的FFmepg Pod 库在这个仓库 https://github.com/debugly/MRFFToolChainPod 里；
一般 pod install 不成功是因为  raw.githubusercontent.com  域名被墙导致的，可以试下是否能 ping 通？不通的话可以绑定这个host试试：
199.232.28.133 raw.githubusercontent.com
